import type { MissionTask } from '../ops/types'
import type { PortfolioCaseStudyPackage } from './types'

export const CASE_STUDY_TEMPLATE_ID = 'template-build-case-study'

export const wardAgentStudioCaseStudy: PortfolioCaseStudyPackage = {
  projectTitle: 'Ward Agent Studio',
  pitch: 'A visual student portfolio and career lab for turning projects, learning notes, prompts, and internship prep into proof-of-work.',
  problem: 'Ward needed something useful as a semester-4 student: a place to stop collecting random experiments, choose the right projects to finish, and turn real work into CV, GitHub, and portfolio material.',
  solution: 'Ward Agent Studio turns a focused two-room isometric workspace into a student Portfolio Factory. The Main Office handles project choices, learning plans, CV notes, and internship prep, while the Quantum Core Lab handles repo polish, proof screenshots, and artifact output.',
  keyFeatures: [
    'Focused two-room isometric workspace with Main Office and Quantum Core Lab.',
    'Ward Mission Control dashboard for project audits, learning notes, prompts, CV notes, internship prep, and next steps.',
    'Clickable agents with role, status, progress, current task, and result summaries.',
    'Mission Queue simulation that moves work through project finding, portfolio coaching, GitHub polish, skill planning, CV prep, and done states.',
    'Agent Terminals for chatting with one agent or broadcasting to the visible crew.',
    'Portfolio Case Study mission that generates a local showcase package for README, portfolio pages, CV bullets, and internship applications.',
  ],
  techStack: [
    'React',
    'TypeScript',
    'Vite',
    'CSS modules through a single game UI stylesheet',
    'Local simulated agent operations model',
    'Isometric pixel-art room and character assets',
  ],
  screenshotsChecklist: [
    'Main Office with Ward Mission Control open.',
    'Agent Terminals showing case study progress messages.',
    'Portfolio Case Study Output panel.',
    'Quantum Core Lab build/test area.',
  ],
  demoFlow: [
    'Open Ward Agent Studio and start in Main Office.',
    'Open Ward Mission Control from the title bar.',
    'Start a project audit or the Build One Portfolio Case Study mission.',
    'Watch the Mission Queue and agent status indicators update.',
    'Open Agent Terminals to inspect what each agent is doing.',
    'Open the Case Study Package and copy the useful sections into GitHub or a portfolio page.',
    'Move between Main Office and Quantum Core Lab to show the planning-to-execution flow.',
  ],
  readmeDraft: [
    'Ward Agent Studio is a visual student portfolio and career lab for organizing project audits, learning goals, prompts, CV notes, repo polish, and internship prep.',
    'The app uses a cozy isometric office-and-lab interface where agents act as Portfolio Coach, Project Finder, Skill Mentor, GitHub Polish Agent, CV Agent, and Internship Scout.',
    'The current version runs as a local simulation: agents update progress, post terminal messages, move between rooms, and generate useful portfolio output without requiring a backend AI service.',
    'Future versions can connect these missions to real agent runners, GitHub automation, screenshot capture, and persistent data storage.',
  ],
  portfolioCardCopy: {
    title: 'Ward Agent Studio',
    description: 'A portfolio-ready visual AI agent workspace that helps a student choose better projects, track learning, polish GitHub repos, create CV bullets, and prepare internship material.',
    tags: ['React', 'TypeScript', 'AI Agents', 'Portfolio Tool', 'Game UI'],
  },
  recruiterBullets: [
    'Designed and implemented a focused visual dashboard that turns student portfolio planning into an inspectable product experience.',
    'Built a local mission simulation with agent roles, progress states, terminals, room hotspots, and generated portfolio outputs.',
    'Created a GitHub-ready product narrative with README sections, demo flow, screenshots checklist, and roadmap planning.',
    'Balanced playful game-like visuals with practical student career, CV, and portfolio workflows.',
  ],
  roadmap: [
    'Persist missions, notes, prompts, and job tracker data locally.',
    'Connect project-audit, CV, and GitHub-polish missions to real Codex/OpenAI agent runs.',
    'Add screenshot capture and auto-README artifact export.',
    'Add GitHub issue/PR integration for completed missions.',
    'Add a public portfolio mode with polished project cards.',
  ],
}

export const caseStudyTerminalScript: Array<{ agentId: string; text: string }> = [
  {
    agentId: 'quantum-coordinator',
    text: 'Project Finder: scope locked around choosing finishable projects, not chasing random new ideas.',
  },
  {
    agentId: 'quantum-mission-specialist',
    text: 'Skill Mentor: positioning is student proof-of-work, learning notes, and semester-4 portfolio growth.',
  },
  {
    agentId: 'quantum-systems-engineer',
    text: 'GitHub Polish Agent: repo story is rooms, mission queue, agent inspector, terminals, and real markdown output.',
  },
  {
    agentId: 'quantum-field-tech',
    text: 'Internship Scout: demo path should prove Ward can explain the project quickly to an internship reviewer.',
  },
  {
    agentId: 'assistant-claude',
    text: 'CV Agent: draft bullets should be honest: student-built React/TypeScript app, local artifacts, UI systems, and roadmap.',
  },
  {
    agentId: 'quantum-ops-captain',
    text: 'Portfolio Coach: portfolio angle ready: useful student tool, clear visuals, practical outputs, and GitHub polish.',
  },
]

export function createCaseStudyMissionTasks(now = Date.now()): MissionTask[] {
  return [
    {
      id: `portfolio-${CASE_STUDY_TEMPLATE_ID}-coordinator-${now}`,
      title: 'Scope Ward Agent Studio student case study',
      description: 'Define the smallest useful student portfolio package and coordinate agent handoffs.',
      assignedAgentId: 'quantum-coordinator',
      assignedRole: 'station-coordinator',
      status: 'planning',
      progress: 12,
      currentRoom: 'quantum-core',
      targetSpotId: 'quantum-front-left',
      lastAction: 'Defining student portfolio scope and sections',
      createdAt: now,
      updatedAt: now,
      outputSummary: 'Case study scope: pitch, problem, solution, features, tech stack, screenshots, demo flow, README draft, CV bullets, internship angle, and roadmap.',
      log: ['Student portfolio mission started', 'Scope: GitHub plus CV plus internship package'],
    },
    {
      id: `portfolio-${CASE_STUDY_TEMPLATE_ID}-researcher-${now}`,
      title: 'Analyze student portfolio positioning',
      description: 'Summarize why the app is useful for Ward as a semester-4 student.',
      assignedAgentId: 'quantum-mission-specialist',
      assignedRole: 'station-mission-specialist',
      status: 'researching',
      progress: 18,
      currentRoom: 'quantum-core',
      targetSpotId: 'quantum-reactor-right',
      lastAction: 'Studying product angle for student portfolio and internship reviewers',
      createdAt: now,
      updatedAt: now,
      outputSummary: 'Positioning: a student portfolio lab that makes projects, learning, CV prep, and GitHub polish visible and actionable.',
      log: ['Audience: Ward, internship reviewers, collaborators', 'Use cases: project audit, learning, GitHub polish, CV prep'],
    },
    {
      id: `portfolio-${CASE_STUDY_TEMPLATE_ID}-builder-${now}`,
      title: 'List GitHub-ready product features',
      description: 'Review the current app and turn implemented behavior into clear README and portfolio feature bullets.',
      assignedAgentId: 'quantum-systems-engineer',
      assignedRole: 'station-systems-engineer',
      status: 'coding',
      progress: 26,
      currentRoom: 'quantum-core',
      targetSpotId: 'quantum-reactor-left',
      lastAction: 'Mapping implemented features into GitHub and CV language',
      createdAt: now,
      updatedAt: now,
      outputSummary: 'Features listed: rooms, navigation, mission queue, inspectors, terminals, local artifact writer, and student portfolio package.',
      log: ['GitHub feature inventory started', 'Keeping scope tied to what exists in app'],
    },
    {
      id: `portfolio-${CASE_STUDY_TEMPLATE_ID}-tester-${now}`,
      title: 'Prepare internship demo flow',
      description: 'Check the main demo path and screenshot list for someone reviewing Ward’s project quickly.',
      assignedAgentId: 'quantum-field-tech',
      assignedRole: 'station-field-tech',
      status: 'testing',
      progress: 34,
      currentRoom: 'quantum-core',
      targetSpotId: 'quantum-front-right',
      lastAction: 'Checking Ward Mission Control, terminals, output panel, and room navigation',
      createdAt: now,
      updatedAt: now,
      outputSummary: 'Demo checklist prepared for Control, Queue, Terminals, Case Study Output, and Quantum Core Lab.',
      log: ['Internship demo path drafted', 'Screenshot checklist prepared'],
    },
    {
      id: `portfolio-${CASE_STUDY_TEMPLATE_ID}-archivist-${now}`,
      title: 'Draft CV and README-ready case study',
      description: 'Write the portfolio story in a format Ward can reuse for GitHub, CV, and internship prep.',
      assignedAgentId: 'assistant-claude',
      assignedRole: 'assistant',
      status: 'reviewing',
      progress: 42,
      currentRoom: 'main-office',
      targetSpotId: 'spot-2',
      lastAction: 'Writing README and case study sections',
      createdAt: now,
      updatedAt: now,
      outputSummary: 'README-ready text and CV angle created in the Case Study Package and docs/case-study artifact.',
      log: ['README draft assembled', 'CV angle prepared', 'Case study artifact ready for review'],
    },
    {
      id: `portfolio-${CASE_STUDY_TEMPLATE_ID}-curator-${now}`,
      title: 'Write student portfolio copy',
      description: 'Turn the project into short, useful bullets for GitHub, CV, LinkedIn, and internship applications.',
      assignedAgentId: 'quantum-ops-captain',
      assignedRole: 'station-ops-captain',
      status: 'reviewing',
      progress: 38,
      currentRoom: 'quantum-core',
      targetSpotId: 'quantum-left-console',
      lastAction: 'Converting product work into student-friendly portfolio bullets',
      createdAt: now,
      updatedAt: now,
      outputSummary: 'Portfolio bullets emphasize product thinking, TypeScript UI work, local artifact output, and student project storytelling.',
      log: ['Portfolio card copy drafted', 'CV bullets drafted'],
    },
  ]
}
