import type { PortfolioDashboardData } from './types'

export const portfolioDashboardData: PortfolioDashboardData = {
  projectIdeas: [
    {
      id: 'idea-project-audit',
      title: 'Current Projects Audit',
      description: 'Scan Ward’s project folders and rank which repos deserve portfolio time first.',
      status: 'planning',
      priority: 'high',
      owner: 'Project Finder',
      nextAction: 'Pick the top 3 projects and write why each one matters.',
    },
    {
      id: 'idea-agent-studio',
      title: 'Ward Agent Studio',
      description: 'Use this app itself as a polished proof-of-work project.',
      status: 'coding',
      priority: 'high',
      owner: 'Portfolio Coach',
      nextAction: 'Package the app as a student portfolio and career lab.',
    },
    {
      id: 'idea-campus-helper',
      title: 'Campus Helper Tool',
      description: 'A small practical app for notes, deadlines, study plans, or class project tracking.',
      status: 'researching',
      priority: 'medium',
      owner: 'Skill Mentor',
      nextAction: 'Choose one pain point from semester 4 and scope a tiny MVP.',
    },
  ],
  learningRoadmap: [
    {
      id: 'learn-react-ts',
      title: 'React + TypeScript confidence',
      description: 'Understand component state, props, data models, build errors, and UI polish.',
      skill: 'Frontend',
      status: 'researching',
      priority: 'high',
      nextAction: 'Write notes from each Ward Agent Studio change.',
    },
    {
      id: 'learn-github-portfolio',
      title: 'GitHub portfolio workflow',
      description: 'Practice README writing, screenshots, clean commits, project descriptions, and releases.',
      skill: 'Git/GitHub',
      status: 'planning',
      priority: 'high',
      nextAction: 'Make one repo look portfolio-readable this week.',
    },
    {
      id: 'learn-ai-agents',
      title: 'Real AI agent workflow',
      description: 'Learn the difference between simulation, queues, tool use, artifact writing, and real agent loops.',
      skill: 'AI agents',
      status: 'planning',
      priority: 'medium',
      nextAction: 'Turn one simulated mission into a real backend artifact.',
    },
  ],
  promptLibrary: [
    {
      id: 'prompt-project-audit',
      title: 'Project audit prompt',
      description: 'Scan folders, score portfolio value, difficulty, usefulness, and next smallest improvement.',
      category: 'Portfolio',
      status: 'planning',
      priority: 'high',
      nextAction: 'Use it on Ward’s Projects folder.',
    },
    {
      id: 'prompt-readme-polish',
      title: 'README polish prompt',
      description: 'Problem, demo, features, setup, screenshots, tech stack, decisions, and roadmap.',
      category: 'GitHub',
      status: 'done',
      priority: 'high',
      nextAction: 'Apply it to Ward Agent Studio first.',
    },
    {
      id: 'prompt-cv-bullets',
      title: 'CV bullets from project',
      description: 'Turn a project into measurable student-friendly bullets without fake work experience.',
      category: 'Career',
      status: 'planning',
      priority: 'medium',
      nextAction: 'Generate bullets from the finished case study.',
    },
  ],
  jobHuntTracker: [
    {
      id: 'job-internship-target',
      company: 'Internship target',
      role: 'Frontend / AI Tools Intern',
      status: 'planning',
      priority: 'high',
      nextAction: 'Prepare 2 polished repos before applying.',
    },
    {
      id: 'job-campus-network',
      company: 'Campus / community',
      role: 'Student developer opportunities',
      status: 'researching',
      priority: 'medium',
      nextAction: 'List clubs, competitions, labs, or freelance-style campus problems.',
    },
    {
      id: 'job-open-source',
      company: 'Open source profile',
      role: 'Beginner contributor',
      status: 'idle',
      priority: 'low',
      nextAction: 'Pick one small documentation or UI issue after portfolio v1 is clean.',
    },
  ],
  buildLog: [
    {
      id: 'log-student-positioning',
      title: 'Student portfolio direction',
      description: 'Ward Agent Studio is now positioned around student proof-of-work, not generic company ops.',
      status: 'done',
      priority: 'high',
      owner: 'Portfolio Coach',
      nextAction: 'Make the dashboard explain what output Ward gets.',
    },
    {
      id: 'log-real-output',
      title: 'Real artifact loop',
      description: 'The case-study mission writes markdown files, so the app can produce something outside the UI.',
      status: 'coding',
      priority: 'high',
      owner: 'GitHub Polish Agent',
      nextAction: 'Add more real artifact missions later: repo audit, CV pack, and learning sprint.',
    },
    {
      id: 'log-cv-ready',
      title: 'CV proof material',
      description: 'Projects need clear bullets, screenshots, and demo flow before they belong on a CV.',
      status: 'planning',
      priority: 'high',
      owner: 'CV Agent',
      nextAction: 'Generate CV bullets from the strongest project first.',
    },
  ],
  todayNextSteps: [
    {
      id: 'today-audit',
      title: 'Audit current projects',
      description: 'Find the top projects Ward should finish instead of starting random new ones.',
      status: 'planning',
      priority: 'high',
      owner: 'Project Finder',
      nextAction: 'Rank projects by usefulness, finish time, and portfolio impact.',
    },
    {
      id: 'today-polish-one',
      title: 'Polish one repo',
      description: 'One clean repo beats ten half-finished experiments.',
      status: 'coding',
      priority: 'high',
      owner: 'GitHub Polish Agent',
      nextAction: 'README, screenshots, setup steps, and roadmap.',
    },
    {
      id: 'today-cv',
      title: 'Create CV bullets',
      description: 'Turn project work into honest student-friendly proof for CV and LinkedIn.',
      status: 'planning',
      priority: 'medium',
      owner: 'CV Agent',
      nextAction: 'Write 3 bullets for Ward Agent Studio after the case study is done.',
    },
  ],
}
