import type { PortfolioDashboardData } from './types'

export const portfolioDashboardData: PortfolioDashboardData = {
  projectIdeas: [
    {
      id: 'idea-agent-studio',
      title: 'Ward Agent Studio',
      description: 'Turn this visual office into a real portfolio command center.',
      status: 'coding',
      priority: 'high',
      owner: 'Portfolio Curator',
      nextAction: 'Ship a clean v1 with screenshots and README.',
    },
    {
      id: 'idea-prompt-vault',
      title: 'Prompt Vault',
      description: 'Save prompts, versions, use cases, and best outputs for repeatable work.',
      status: 'planning',
      priority: 'medium',
      owner: 'Researcher',
      nextAction: 'Design the smallest useful prompt card.',
    },
    {
      id: 'idea-learning-companion',
      title: 'Learning Companion',
      description: 'Track what Ward learns, mistakes found, and the next tiny exercise.',
      status: 'researching',
      priority: 'medium',
      owner: 'Career Agent',
      nextAction: 'Pick one skill path for this week.',
    },
  ],
  learningRoadmap: [
    {
      id: 'learn-react',
      title: 'React app state',
      description: 'Understand how room state, panels, agents, and missions connect.',
      skill: 'Frontend',
      status: 'researching',
      priority: 'high',
      nextAction: 'Write notes from the Mission Control refactor.',
    },
    {
      id: 'learn-git',
      title: 'GitHub portfolio flow',
      description: 'Practice commit hygiene, README writing, screenshots, and releases.',
      skill: 'Git/GitHub',
      status: 'planning',
      priority: 'high',
      nextAction: 'Prepare repo name and first portfolio commit.',
    },
    {
      id: 'learn-ai-agents',
      title: 'Agent workflows',
      description: 'Separate demo simulation from future real file/build automation.',
      skill: 'AI workflow',
      status: 'planning',
      priority: 'medium',
      nextAction: 'Document what is simulated now and what becomes real later.',
    },
  ],
  promptLibrary: [
    {
      id: 'prompt-build-mission',
      title: 'Build mission prompt',
      description: 'Goal, constraints, agent roles, verification, screenshots, expected result.',
      category: 'Implementation',
      status: 'done',
      priority: 'high',
      nextAction: 'Reuse for every portfolio feature.',
    },
    {
      id: 'prompt-project-case-study',
      title: 'Project case study prompt',
      description: 'Problem, process, screenshots, technical choices, outcome, next steps.',
      category: 'Portfolio',
      status: 'planning',
      priority: 'medium',
      nextAction: 'Generate case study draft after screenshots.',
    },
    {
      id: 'prompt-job-pack',
      title: 'Job application pack prompt',
      description: 'Company notes, role fit, CV bullets, cover letter angle, follow-up message.',
      category: 'Career',
      status: 'planning',
      priority: 'medium',
      nextAction: 'Create a reusable application checklist.',
    },
  ],
  jobHuntTracker: [
    {
      id: 'job-frontend-intern',
      company: 'Portfolio target',
      role: 'Junior Frontend / AI Tools Builder',
      status: 'planning',
      priority: 'high',
      nextAction: 'Finish Ward Agent Studio README and screenshots.',
    },
    {
      id: 'job-freelance-dashboard',
      company: 'Freelance demo',
      role: 'Dashboard / Automation Builder',
      status: 'researching',
      priority: 'medium',
      nextAction: 'Prepare a short demo video script.',
    },
    {
      id: 'job-open-source',
      company: 'Open source profile',
      role: 'Contributor',
      status: 'idle',
      priority: 'low',
      nextAction: 'Pick one small issue after this app is pushed.',
    },
  ],
  buildLog: [
    {
      id: 'log-multi-room',
      title: 'Multi-room orbit workspace',
      description: 'Office, command deck, quantum lab, and greenhouse are connected.',
      status: 'done',
      priority: 'high',
      owner: 'Builder',
      nextAction: 'Keep room navigation stable while adding product features.',
    },
    {
      id: 'log-agent-ops',
      title: 'Agent Ops simulation',
      description: 'Agents expose status, progress, current room, and clickable inspectors.',
      status: 'coding',
      priority: 'high',
      owner: 'Tester',
      nextAction: 'Verify Start Mission creates useful work items.',
    },
    {
      id: 'log-github-ready',
      title: 'GitHub polish',
      description: 'README needs product framing, run steps, screenshots, and roadmap.',
      status: 'planning',
      priority: 'high',
      owner: 'Archivist',
      nextAction: 'Update README after build verification.',
    },
  ],
  todayNextSteps: [
    {
      id: 'today-ship-v1',
      title: 'Ship Ward Agent Studio v1',
      description: 'Make the app explain itself and prove that agents can run demo missions.',
      status: 'coding',
      priority: 'high',
      owner: 'Coordinator',
      nextAction: 'Start one mission template and inspect the queue.',
    },
    {
      id: 'today-capture',
      title: 'Capture proof screenshots',
      description: 'Use screenshots as GitHub portfolio evidence.',
      status: 'testing',
      priority: 'high',
      owner: 'Tester',
      nextAction: 'Capture Mission Control, queue, lab, and greenhouse panels.',
    },
    {
      id: 'today-push',
      title: 'Prepare GitHub push',
      description: 'After review, create a clean commit and push to Ward-owned repo.',
      status: 'planning',
      priority: 'medium',
      owner: 'Archivist',
      nextAction: 'Confirm repo name and remote before pushing.',
    },
  ],
}
