import type { MissionTask } from '../ops/types'
import type { PortfolioMissionTemplate } from './types'

export const RECOMMENDED_STUDENT_TEMPLATE_ID = 'template-current-projects-plan'

export const portfolioMissionTemplates: PortfolioMissionTemplate[] = [
  {
    id: RECOMMENDED_STUDENT_TEMPLATE_ID,
    title: 'Turn My Current Projects Into a Portfolio Plan',
    goal: 'Audit Ward’s current projects and choose what is actually worth finishing first.',
    description: 'Rank projects by usefulness, finish time, portfolio value, CV value, and what to do next.',
    priority: 'high',
    status: 'planning',
    assignedRole: 'station-coordinator',
    assignedAgentId: 'quantum-coordinator',
    currentRoom: 'quantum-core',
    targetSpotId: 'quantum-front-left',
    suggestedAgents: ['Project Finder', 'Portfolio Coach', 'GitHub Polish Agent', 'CV Agent'],
    checklist: ['List current projects', 'Score portfolio value', 'Pick top 3', 'Write next action for each', 'Choose one project to polish first'],
    expectedOutput: 'A ranked project plan so Ward knows exactly what to finish for CV, GitHub, and portfolio.',
  },
  {
    id: 'template-build-case-study',
    title: 'Build One Portfolio Case Study',
    goal: 'Turn Ward Agent Studio itself into a GitHub-ready case study package.',
    description: 'Generate the pitch, problem, solution, features, screenshots checklist, README draft, portfolio copy, CV bullets, and internship angle.',
    priority: 'high',
    status: 'planning',
    assignedRole: 'station-ops-captain',
    assignedAgentId: 'quantum-ops-captain',
    currentRoom: 'quantum-core',
    targetSpotId: 'quantum-left-console',
    suggestedAgents: ['Portfolio Coach', 'GitHub Polish Agent', 'CV Agent', 'Internship Scout'],
    checklist: ['Define case study scope', 'Summarize student portfolio angle', 'List features', 'Verify demo flow', 'Draft README and CV bullets'],
    expectedOutput: 'A compact portfolio package Ward can reuse for GitHub, portfolio pages, CV, and internship applications.',
  },
  {
    id: 'template-github-polish',
    title: 'Polish One GitHub Repo',
    goal: 'Make one project understandable and attractive to someone reviewing Ward’s portfolio.',
    description: 'Clean README, add screenshots checklist, describe tech stack, explain setup, and write roadmap.',
    priority: 'high',
    status: 'reviewing',
    assignedRole: 'station-systems-engineer',
    assignedAgentId: 'quantum-systems-engineer',
    currentRoom: 'quantum-core',
    targetSpotId: 'quantum-reactor-left',
    suggestedAgents: ['GitHub Polish Agent', 'Portfolio Coach'],
    checklist: ['Write product pitch', 'List features', 'Add setup steps', 'Plan screenshots', 'Add roadmap'],
    expectedOutput: 'A GitHub README and repo checklist that makes the project portfolio-ready.',
  },
  {
    id: 'template-cv-project-bullets',
    title: 'Create CV Bullets From Projects',
    goal: 'Turn Ward’s real project work into honest student-friendly CV and LinkedIn bullets.',
    description: 'Extract what Ward built, what tools were used, what problem it solves, and why it shows skill.',
    priority: 'high',
    status: 'planning',
    assignedRole: 'career-agent',
    assignedAgentId: 'assistant-claude',
    currentRoom: 'main-office',
    targetSpotId: 'spot-2',
    suggestedAgents: ['CV Agent', 'Portfolio Coach', 'Internship Scout'],
    checklist: ['Pick one project', 'Write 3 CV bullets', 'Write LinkedIn summary line', 'Write interview story', 'Note missing proof'],
    expectedOutput: 'CV bullets, LinkedIn copy, and interview talking points from projects Ward actually has.',
  },
  {
    id: 'template-learn-skill',
    title: 'Learn One Skill This Week',
    goal: 'Create a tiny weekly learning sprint with notes, practice, and proof of progress.',
    description: 'Choose one skill, break it into exercises, and log what changed after each session.',
    priority: 'medium',
    status: 'researching',
    assignedRole: 'station-mission-specialist',
    assignedAgentId: 'quantum-mission-specialist',
    currentRoom: 'quantum-core',
    targetSpotId: 'quantum-reactor-right',
    suggestedAgents: ['Skill Mentor', 'Portfolio Coach'],
    checklist: ['Pick one skill', 'Collect references', 'Create 3 exercises', 'Write notes', 'Add portfolio proof'],
    expectedOutput: 'A short learning plan plus evidence Ward can keep building on.',
  },
  {
    id: 'template-internship-pack',
    title: 'Prepare Internship Application Pack',
    goal: 'Prepare reusable internship materials without pretending Ward has full-time work experience.',
    description: 'Create target role notes, project proof, CV angle, cover letter angle, and interview prep.',
    priority: 'medium',
    status: 'planning',
    assignedRole: 'station-field-tech',
    assignedAgentId: 'quantum-field-tech',
    currentRoom: 'quantum-core',
    targetSpotId: 'quantum-front-right',
    suggestedAgents: ['Internship Scout', 'CV Agent', 'Portfolio Coach'],
    checklist: ['Pick target internship type', 'Extract project proof', 'Draft cover angle', 'List skill gaps', 'Prepare interview stories'],
    expectedOutput: 'A reusable internship checklist and first draft application material.',
  },
  {
    id: 'template-project-ideas',
    title: 'Find 5 Buildable Student Projects',
    goal: 'Find five practical ideas that are useful for Ward and realistic for semester 4.',
    description: 'Rank ideas by usefulness, build size, learning value, and portfolio value.',
    priority: 'medium',
    status: 'researching',
    assignedRole: 'station-coordinator',
    assignedAgentId: 'quantum-coordinator',
    currentRoom: 'quantum-core',
    targetSpotId: 'quantum-front-left',
    suggestedAgents: ['Project Finder', 'Skill Mentor', 'Portfolio Coach'],
    checklist: ['List 5 ideas', 'Score usefulness', 'Score build size', 'Choose top 1', 'Save rejected ideas'],
    expectedOutput: 'A ranked idea list with one recommended build mission.',
  },
  {
    id: 'template-demo-proof',
    title: 'Make Demo Proof For One Project',
    goal: 'Make a project easy to understand in a GitHub README, CV, or short demo video.',
    description: 'Capture the best screens and write the click path for a simple demo.',
    priority: 'medium',
    status: 'testing',
    assignedRole: 'station-systems-engineer',
    assignedAgentId: 'quantum-systems-engineer',
    currentRoom: 'quantum-core',
    targetSpotId: 'quantum-reactor-left',
    suggestedAgents: ['GitHub Polish Agent', 'Portfolio Coach'],
    checklist: ['Open main screen', 'Capture dashboard', 'Capture important result', 'Write demo steps', 'Add README screenshot notes'],
    expectedOutput: 'A screenshot plan and a short demo script for one repo.',
  },
]

export function createMissionFromTemplate(templateId: string, now = Date.now()): MissionTask | null {
  const template = portfolioMissionTemplates.find(item => item.id === templateId)
  if (!template) return null

  return {
    id: `portfolio-${template.id}-${now}`,
    title: template.title,
    description: template.description,
    assignedAgentId: template.assignedAgentId,
    assignedRole: template.assignedRole,
    status: template.status,
    progress: Math.min(template.status === 'coding' ? 18 : template.status === 'testing' ? 28 : 8, 35),
    currentRoom: template.currentRoom,
    targetSpotId: template.targetSpotId,
    lastAction: `Started: ${template.goal}`,
    createdAt: now,
    updatedAt: now,
    resultSummary: undefined,
    outputSummary: `Expected output: ${template.expectedOutput}`,
    log: [
      `Mission started from template: ${template.title}`,
      `Agents: ${template.suggestedAgents.join(', ')}`,
      `Checklist: ${template.checklist[0]}`,
    ],
  }
}
