import type { MissionTask } from '../ops/types'
import type { PortfolioMissionTemplate } from './types'

export const portfolioMissionTemplates: PortfolioMissionTemplate[] = [
  {
    id: 'template-build-project',
    title: 'Build a portfolio project from an idea',
    goal: 'Turn one practical idea into a small working app Ward can show on GitHub.',
    description: 'Pick one idea, define the v1 scope, build the first usable screen, then verify it.',
    priority: 'high',
    status: 'planning',
    assignedRole: 'station-coordinator',
    assignedAgentId: 'station-coordinator',
    currentRoom: 'station-command',
    targetSpotId: 'station-strategy',
    suggestedAgents: ['Coordinator', 'Researcher', 'Builder', 'Tester', 'Archivist'],
    checklist: ['Choose one idea', 'Define smallest useful v1', 'Build first interaction', 'Run build', 'Write README notes'],
    expectedOutput: 'A working app slice, screenshot proof, and a GitHub-ready summary.',
  },
  {
    id: 'template-improve-studio',
    title: 'Improve this Ward Agent Studio app',
    goal: 'Make the current app more useful as Ward’s personal AI operations portfolio.',
    description: 'Add one compact feature that improves missions, learning, prompts, or career prep.',
    priority: 'high',
    status: 'coding',
    assignedRole: 'assistant',
    assignedAgentId: 'assistant-claude',
    currentRoom: 'main-office',
    targetSpotId: 'spot-2',
    suggestedAgents: ['Coordinator', 'Builder', 'Tester', 'Portfolio Curator'],
    checklist: ['Pick one focused improvement', 'Patch the UI', 'Keep rooms stable', 'Run build', 'Capture screenshot'],
    expectedOutput: 'One finished app improvement with visible before/after value.',
  },
  {
    id: 'template-learn-skill',
    title: 'Learn one skill this week',
    goal: 'Create a tiny learning sprint with notes, practice, and proof of progress.',
    description: 'Choose one skill, break it into exercises, and log what changed after each session.',
    priority: 'medium',
    status: 'researching',
    assignedRole: 'station-mission-specialist',
    assignedAgentId: 'greenhouse-mission-specialist',
    currentRoom: 'orbital-greenhouse',
    targetSpotId: 'greenhouse-right-row',
    suggestedAgents: ['Researcher', 'Career Agent', 'Archivist'],
    checklist: ['Pick one skill', 'Collect references', 'Create 3 exercises', 'Write notes', 'Add portfolio proof'],
    expectedOutput: 'A short learning plan plus notes Ward can keep building on.',
  },
  {
    id: 'template-readme',
    title: 'Prepare GitHub README for a project',
    goal: 'Make one project understandable and attractive to someone reviewing Ward’s portfolio.',
    description: 'Explain the problem, features, setup, screenshots, stack, and roadmap.',
    priority: 'high',
    status: 'reviewing',
    assignedRole: 'station-coordinator',
    assignedAgentId: 'station-coordinator',
    currentRoom: 'station-command',
    targetSpotId: 'station-ops',
    suggestedAgents: ['Archivist', 'Portfolio Curator', 'Tester'],
    checklist: ['Write product pitch', 'List features', 'Add setup steps', 'Add screenshots', 'Add roadmap'],
    expectedOutput: 'A GitHub README that makes the project portfolio-ready.',
  },
  {
    id: 'template-job-pack',
    title: 'Create job application pack',
    goal: 'Prepare reusable job hunt materials without pretending Ward needs a job today.',
    description: 'Create CV bullets, project highlights, a cover letter angle, and interview notes.',
    priority: 'medium',
    status: 'planning',
    assignedRole: 'station-mission-specialist',
    assignedAgentId: 'station-mission-specialist',
    currentRoom: 'station-command',
    targetSpotId: 'station-research',
    suggestedAgents: ['Career Agent', 'Portfolio Curator', 'Archivist'],
    checklist: ['Pick target role', 'Extract portfolio bullets', 'Draft cover angle', 'Prepare interview stories'],
    expectedOutput: 'A reusable application checklist and first draft material.',
  },
  {
    id: 'template-research-ideas',
    title: 'Research 5 project ideas',
    goal: 'Find five buildable ideas that are useful for Ward and easy to demonstrate.',
    description: 'Rank ideas by usefulness, build size, learning value, and portfolio value.',
    priority: 'medium',
    status: 'researching',
    assignedRole: 'station-mission-specialist',
    assignedAgentId: 'greenhouse-mission-specialist',
    currentRoom: 'orbital-greenhouse',
    targetSpotId: 'greenhouse-front-console',
    suggestedAgents: ['Researcher', 'Coordinator', 'Portfolio Curator'],
    checklist: ['List 5 ideas', 'Score usefulness', 'Score build size', 'Choose top 1', 'Save rejected ideas'],
    expectedOutput: 'A ranked idea list with one recommended build mission.',
  },
  {
    id: 'template-screenshots',
    title: 'Polish screenshots and demo flow',
    goal: 'Make the app easy to understand in a GitHub README or short demo video.',
    description: 'Capture the best screens and write the click path for a simple demo.',
    priority: 'medium',
    status: 'testing',
    assignedRole: 'station-field-tech',
    assignedAgentId: 'quantum-field-tech',
    currentRoom: 'quantum-core',
    targetSpotId: 'quantum-front-right',
    suggestedAgents: ['Tester', 'Designer', 'Portfolio Curator'],
    checklist: ['Open main screen', 'Capture dashboard', 'Capture mission queue', 'Capture lab flow', 'Write demo steps'],
    expectedOutput: 'A screenshot set and a short demo script.',
  },
  {
    id: 'template-case-study',
    title: 'Write a project case study',
    goal: 'Turn a finished project into a story that shows thinking, taste, and execution.',
    description: 'Document the problem, constraints, decisions, screenshots, bugs, and next steps.',
    priority: 'medium',
    status: 'reviewing',
    assignedRole: 'station-coordinator',
    assignedAgentId: 'station-coordinator',
    currentRoom: 'station-command',
    targetSpotId: 'station-strategy',
    suggestedAgents: ['Archivist', 'Portfolio Curator', 'Tester'],
    checklist: ['Define problem', 'List constraints', 'Explain decisions', 'Add screenshots', 'Write next steps'],
    expectedOutput: 'A compact case study Ward can paste into a portfolio page.',
  },
]

export function createMissionFromTemplate(templateId: string, now = Date.now()): MissionTask | null {
  const template = portfolioMissionTemplates.find(item => item.id === templateId)
  if (!template) return null

  return {
    id: `portfolio-${template.id}-${now}`,
    title: template.title,
    description: template.description,
    assignedAgentId: template.assignedAgentId,
    assignedRole: template.assignedRole,
    status: template.status,
    progress: Math.min(template.status === 'coding' ? 18 : template.status === 'testing' ? 28 : 8, 35),
    currentRoom: template.currentRoom,
    targetSpotId: template.targetSpotId,
    lastAction: `Started: ${template.goal}`,
    createdAt: now,
    updatedAt: now,
    resultSummary: undefined,
    outputSummary: `Expected output: ${template.expectedOutput}`,
    log: [
      `Mission started from template: ${template.title}`,
      `Agents: ${template.suggestedAgents.join(', ')}`,
      `Checklist: ${template.checklist[0]}`,
    ],
  }
}
