import type { MissionTask } from './types'

export function createDemoMissions(now = Date.now()): MissionTask[] {
  return [
    {
      id: 'mission-ideas',
      title: 'Research three small app ideas',
      description: 'Find tiny app ideas that Ward can actually build and use this week.',
      assignedAgentId: 'greenhouse-mission-specialist',
      assignedRole: 'station-mission-specialist',
      status: 'researching',
      progress: 18,
      currentRoom: 'orbital-greenhouse',
      targetSpotId: 'greenhouse-right-row',
      lastAction: 'Scanning seed ideas in the grow bay',
      createdAt: now - 9 * 60_000,
      updatedAt: now,
      log: ['Opened idea backlog', 'Sorting ideas by usefulness and build size'],
    },
    {
      id: 'mission-prototype',
      title: 'Build first usable prototype',
      description: 'Turn the selected idea into a first-screen working prototype.',
      assignedAgentId: 'quantum-systems-engineer',
      assignedRole: 'station-systems-engineer',
      status: 'coding',
      progress: 36,
      currentRoom: 'quantum-core',
      targetSpotId: 'quantum-reactor-left',
      lastAction: 'Wiring prototype state and interactions',
      createdAt: now - 7 * 60_000,
      updatedAt: now,
      log: ['Created first UI shell', 'Connecting prototype state'],
    },
    {
      id: 'mission-smoke-test',
      title: 'Run UI smoke test',
      description: 'Click through the current build and catch obvious broken flows.',
      assignedAgentId: 'quantum-field-tech',
      assignedRole: 'station-field-tech',
      status: 'testing',
      progress: 42,
      currentRoom: 'quantum-core',
      targetSpotId: 'quantum-front-right',
      lastAction: 'Checking room navigation and panels',
      createdAt: now - 5 * 60_000,
      updatedAt: now,
      log: ['Opened app in browser', 'Testing door transitions'],
    },
    {
      id: 'mission-assets',
      title: 'Review generated room assets',
      description: 'Review station, reactor, and greenhouse art for readability and obvious artifacts.',
      assignedAgentId: 'station-coordinator',
      assignedRole: 'station-coordinator',
      status: 'reviewing',
      progress: 61,
      currentRoom: 'station-command',
      targetSpotId: 'station-strategy',
      lastAction: 'Comparing screenshots against room specs',
      createdAt: now - 8 * 60_000,
      updatedAt: now,
      log: ['Checked Station Command Deck', 'Flagged unsafe character spots', 'Reviewing Greenhouse Bay'],
    },
    {
      id: 'mission-summary',
      title: 'Write learning summary',
      description: 'Capture what changed and what Ward can try next.',
      assignedAgentId: 'greenhouse-coordinator',
      assignedRole: 'station-coordinator',
      status: 'planning',
      progress: 24,
      currentRoom: 'orbital-greenhouse',
      targetSpotId: 'greenhouse-front-console',
      lastAction: 'Collecting notes from completed work',
      createdAt: now - 4 * 60_000,
      updatedAt: now,
      log: ['Created summary outline', 'Waiting for test result'],
    },
    {
      id: 'mission-launch',
      title: 'Prepare launch checklist',
      description: 'Keep the next steps clear: run build, verify screenshots, then package notes.',
      assignedAgentId: 'assistant-claude',
      assignedRole: 'assistant',
      status: 'planning',
      progress: 50,
      currentRoom: 'main-office',
      targetSpotId: 'spot-2',
      lastAction: 'Keeping the rollout checklist tidy',
      createdAt: now - 6 * 60_000,
      updatedAt: now,
      log: ['Build command ready', 'Screenshot checklist ready'],
    },
  ]
}
